# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  Fastapi-engine:
    build: .
    container_name: api
    ports:
      - 8001:8001
    volumes:
      - .:/app
      - /data:/app/data
      - /vector_db:/app/vector_db
    environment:
      - DATA_PATH=/app/data
      - DB_PATH=/app/vector_db
    command: uvicorn api.main:app --reload --port 8001
  
  Django-engine:
    build: .
    container_name: web_app
    ports:
      - 8000:8000
    environment:
      - FASTAPI_URL=http://api:8001
      - DJANGO_SETTINGS_MODULE=home.settings
    depends_on:
      - Fastapi-engine
    volumes:
      - .:/app
    command: gunicorn home.wsgi:application --bind 0.0.0.0:8000
  
